#version 300 es
precision highp float;

in vec2 vTexCoord;
out vec4 fragColor;

uniform float uControlX;       //  0.0 (Convex core) -> 1.0 (Kepler-Poinsot spikes)
uniform float uControlY;       //  0.0 (Icosahedron 20) -> 0.5 (Crystal 60) -> 1.0 (Dodecahedron 12)
uniform float uColorMethod;    //  0 Chamber | 1 Depth | 2 Normal
uniform float uHueOffset;
uniform float uSaturation;
uniform float uBrightness;
uniform float uOpacity;
uniform float uEdgeThickness;
uniform float uEdgeBrightness;
uniform float uZoom;
uniform float uRotateX;
uniform float uRotateY;
uniform float uRotateZ;

uniform vec3 uH3Normals[60]; // Y-Axis: The 60 planes generated by Kotlin this frame
uniform int uPlaneCount;     // NEW: Tells the shader how many unique planes exist
uniform float uSupportH;     // Base radius (default to your old h0: 0.82)
uniform float uAlpha;
uniform vec2  uResolution;
uniform float uTime;

const float PI  = 3.14159265358979323846;
const float PHI = 1.61803398874989484820;

mat3 rotateX(float a){float c=cos(a),s=sin(a);return mat3(1,0,0,0,c,-s,0,s,c);}
mat3 rotateY(float a){float c=cos(a),s=sin(a);return mat3(c,0,s,0,1,0,-s,0,c);}
mat3 rotateZ(float a){float c=cos(a),s=sin(a);return mat3(c,-s,0,s,c,0,0,0,1);}

vec3 palette(float t,vec3 a,vec3 b,vec3 c,vec3 d){return a+b*cos(6.2831853*(c*t+d));}
vec3 adjustColor(vec3 col,float sat,float bright){
    float g=dot(col,vec3(0.299,0.587,0.114));
    return max(vec3(0.0),mix(vec3(g),col,sat)*bright);
}

// =============================================================================
// Icosahedral Continuous Stellation Signed Distance Field (k-th max)
// =============================================================================
float mapSDF(vec3 p, out float outEdge, out vec3 outColorCoord, out float outDepth) {
    float u[6] = float[6](-1e5, -1e5, -1e5, -1e5, -1e5, -1e5);

    // Loop exactly uPlaneCount times. No deduplication logic needed here!
    for (int i = 0; i < uPlaneCount; i++) {
        float d = dot(p, uH3Normals[i]);
        
        // Branchless-friendly cascading sort
        if (d > u[0])      { u[5]=u[4]; u[4]=u[3]; u[3]=u[2]; u[2]=u[1]; u[1]=u[0]; u[0]=d; }
        else if (d > u[1]) { u[5]=u[4]; u[4]=u[3]; u[3]=u[2]; u[2]=u[1]; u[1]=d; }
        else if (d > u[2]) { u[5]=u[4]; u[4]=u[3]; u[3]=u[2]; u[2]=d; }
        else if (d > u[3]) { u[5]=u[4]; u[4]=u[3]; u[3]=d; }
        else if (d > u[4]) { u[5]=u[4]; u[4]=d; }
        else if (d > u[5]) { u[5]=d; }
    }

    float k_float = mix(0.0, 4.999, clamp(uControlX, 0.0, 1.0)); 
    int k_int = int(floor(k_float));
    float blend = fract(k_float);

    float d_curr = u[k_int] - uSupportH;
    float d_next = u[k_int + 1] - uSupportH;

    float totalSdf = mix(d_curr, d_next, blend);

    float edge_curr = u[k_int] - u[k_int + 1];
    float edge_next = u[k_int + 1] - u[min(k_int + 2, 5)];
    outEdge = mix(edge_curr, edge_next, blend);

    vec3 color_curr = vec3(u[k_int], u[k_int + 1], u[min(k_int + 2, 5)]);
    vec3 color_next = vec3(u[k_int + 1], u[min(k_int + 2, 5)], u[min(k_int + 3, 5)]);
    outColorCoord = mix(color_curr, color_next, blend);
    outDepth = length(p);

    return totalSdf;
}

vec3 getNormal(vec3 p){
    float dE,dD; vec3 dC;
    vec2 e=vec2(0.001,0.0);
    float d=mapSDF(p,dE,dC,dD);
    return normalize(vec3(
        mapSDF(p+e.xyy,dE,dC,dD)-d,
        mapSDF(p+e.yxy,dE,dC,dD)-d,
        mapSDF(p+e.yyx,dE,dC,dD)-d));
}

void main(){
    vec2 uv=vTexCoord*2.0-1.0;
    uv.x*=uResolution.x/uResolution.y;

    float zoom=clamp(uZoom,0.1,5.0);
    vec3 ro=vec3(0.0,0.0,-3.8/zoom);
    vec3 rd=normalize(vec3(uv,1.4));
    mat3 rot=rotateZ(uRotateZ)*rotateY(uRotateY)*rotateX(uRotateX);
    ro=rot*ro; rd=rot*rd;

    vec3 palA=vec3(0.5),palB=vec3(0.5),palC=vec3(1.0),palD=vec3(0.0,0.33,0.67);

    vec4  acc=vec4(0.0);
    float t=max(0.0,(3.8-3.0)/zoom);
    float opacity=clamp(uOpacity,0.0,1.0);
    float edgeThick=clamp(uEdgeThickness,0.0,0.15);

    for(int i=0;i<120;i++){
        vec3  p=ro+rd*t;
        float edge,depth; vec3 cC;
        float dist=mapSDF(p,edge,cC,depth);

        if(dist<0.003){
            vec3  n=getNormal(p);
            vec3  lD=normalize(vec3(0.577,0.577,-0.577));
            float diff=max(0.25,dot(n,lD));
            float spec=pow(max(0.0,dot(reflect(-lD,n),-rd)),16.0)*0.4;

            vec3 col;
            if(uColorMethod<0.66){
                float cc = cC.x * 3.0 + cC.y * 2.0 + cC.z * 1.0;
                col=palette(fract(cc*0.5+uHueOffset),palA,palB,palC,palD);
            }else if(uColorMethod<1.33){
                col=palette(clamp((depth-0.7)/1.6,0.0,1.0)+uHueOffset,palA,palB,palC,palD);
            }else{
                vec3 nt=abs(n);
                col=palette(fract((nt.x+nt.y*2.0+nt.z*3.0)*0.33+uHueOffset),palA,palB,palC,palD);
            }
            col=adjustColor(col,uSaturation,uBrightness)*diff+vec3(spec);

            if(edgeThick>0.001){
                float ef=1.0-smoothstep(0.0,edgeThick,edge);
                col=mix(col,adjustColor(vec3(1.0)-col*0.5,uSaturation,uBrightness*uEdgeBrightness),ef);
            }

            float w=(1.0-acc.a)*opacity;
            acc.rgb+=col*w; acc.a+=w;
            if(acc.a>0.96) break;
            t+=max(0.006/zoom,dist+0.006/zoom);
        }else{
            // Lower step multiplier prevents overstepping on acute needle ridges
            t+=max(0.003/zoom,dist*0.5);
        }
        if(t>(3.8+3.5)/zoom) break;
    }

    if(acc.a<0.9){
        float gE,gD; vec3 gC;
        float gd=mapSDF(ro+rd*(3.8/zoom),gE,gC,gD);
        acc.rgb+=palette(uHueOffset,palA,palB,palC,palD)*exp(-max(0.0,gd)*4.0)*0.15*uBrightness*(1.0-acc.a);
    }

    fragColor=vec4(acc.rgb,acc.a*uAlpha);
}
