package llm.slop.liquidlsd.ui

import llm.slop.liquidlsd.audio.AudioEngine
import llm.slop.liquidlsd.audio.AudioTarget

data class AppSettings(
    val guiScalePercent: Int = 100,
    val audioEngineEnabled: Boolean = true,
    val audioBackend: AudioEngine.AudioBackendMode = AudioEngine.AudioBackendMode.AUTO,
    val audioDeviceName: String = "",
    val audioInputGain: Float = 1.0f,
    val audioBpmLocked: Boolean = true,
    val audioManualBpm: Float = 120.0f,
    val audioBeatTarget: AudioTarget = AudioTarget.LOW,
    val audioBpmFloor: Int = 40,
    val audioBpmCeiling: Int = 200,
    val audioTransitionAlpha: Float = 120.0f,
    val audioTrackingInertia: Float = 2.0f,
    val backgroundVideoEnabled: Boolean = false,
    val cleanModeEnabled: Boolean = false,
    val randomizationEnabled: Boolean = true,
    val autoVjDirtyBehavior: UITheme.AutoVjDirtyBehavior = UITheme.AutoVjDirtyBehavior.AUTO_DISCARD,
    val activeMidiProfile: String = "default",
    val queueKeyTrigger: UITheme.QueueKeyTrigger = UITheme.QueueKeyTrigger.NONE,
    val tooltipsEnabled: Boolean = true,
    val maxFps: Int = 30,
    val startupBehavior: UITheme.StartupBehavior = UITheme.StartupBehavior.PREVIOUS_SESSION,
    val libraryMode: UITheme.LibraryMode = UITheme.LibraryMode.HALF,
    val theme: UITheme.Theme = UITheme.Theme.BORING,
    val showMidiCol: Boolean = true,
    val showLfoCol: Boolean = true,
    val showSeqCol: Boolean = true,
    val showAudioCol: Boolean = true,
    val showTriggerCol: Boolean = true,
    val col1Ratio: Float = 0.30f,
    val col2Ratio: Float = 0.40f,
    val libraryRatio: Float = 0.50f,
    val lastCustomLibraryRatio: Float = 0.50f,
    val gridCellRatio: Float = 1.0f,
    val renderResolutionPreset: UITheme.ResolutionPreset = UITheme.ResolutionPreset.RES_1080P,
    val customRenderWidth: Int = 1920,
    val customRenderHeight: Int = 1080,
    val outputScaleMode: UITheme.OutputScaleMode = UITheme.OutputScaleMode.FIT,
    val recordingDirectory: String = "",
    val recordingIncludeAudio: Boolean = true,
    val recordingBitrateMbps: Int = 12,
    val recordingFps: Int = 60,
    val settingsWidth: Float = 640f,
    val settingsHeight: Float = 520f,
    val framelessWindow: Boolean = true
)
