// Mandala parameter -> shader uniform mapping. A port of Mandala.pickRecipe / hueSweepCycles /
// setupUniforms (src/main/kotlin/llm/slop/liquidlsd/rendering/Mandala.kt); the selection logic is
// pinned to the desktop by web/tools/mandala_vectors.json (node --test web/tools/mandala.test.mjs).
// The recipe table is web/mandala_recipes.json, generated by scripts/sync_web.py.

export const TARGET_RADIUS = 2.0;

/** Rows are [a, b, c, d, petals], in the desktop library order. */
export class MandalaRecipes {
  constructor(table) {
    this.byPetals = new Map();
    for (const [a, b, c, d, petals] of table.recipes) {
      if (!this.byPetals.has(petals)) this.byPetals.set(petals, []);
      this.byPetals.get(petals).push({ a, b, c, d, petals });
    }
    this.petals = [...this.byPetals.keys()].sort((x, y) => x - y);
    this.hueCache = new Map();
  }

  closestPetals(target) {
    if (!this.petals.length) return 3;
    let best = this.petals[0];
    for (const p of this.petals) if (Math.abs(p - target) < Math.abs(best - target)) best = p;
    return best; // ties keep the smaller, as minByOrNull does on a sorted list
  }

  pickRecipe(lobes, select) {
    const list = this.byPetals.get(this.closestPetals(lobes));
    if (!list || !list.length) return null;
    const i = Math.min(list.length - 1, Math.max(0, Math.round(select * (list.length - 1))));
    return list[i];
  }

  symmetricHueCycles(petals) {
    const p = Math.max(1, petals);
    let opts = this.hueCache.get(p);
    if (!opts) {
      const set = new Set();
      for (let i = 1; i <= p; i++) if (p % i === 0) set.add(i);
      for (let i = 1; i <= 4; i++) set.add(p * i);
      opts = [...set].sort((x, y) => x - y);
      this.hueCache.set(p, opts);
    }
    return opts;
  }

  hueSweepCycles(petals, rawSweep) {
    const opts = this.symmetricHueCycles(petals);
    const i = opts.length > 1
      ? Math.min(opts.length - 1, Math.max(0, Math.round(rawSweep * (opts.length - 1)))) : 0;
    return opts[i];
  }

  /**
   * Shader-ready uniforms from evaluated parameter values. `get(name, fallback)` returns the
   * evaluated value of a Mandala parameter (Lobes, Recipe Select, L1..L4, Thickness, ...).
   */
  uniforms(get) {
    const recipe = this.pickRecipe(Math.round(get('Lobes', 4)), get('Recipe Select', 0))
      ?? { a: 3, b: 4, c: 5, d: 7, petals: 3 };
    // Fallbacks are the defaults in library/sources/mandala/meta.json
    const l = [get('L1', 0.4), get('L2', 0.3), get('L3', 0.2), get('L4', 0.1)];
    const sum = l.reduce((s, v) => s + Math.abs(v), 0);
    const scale = sum > 1e-5 ? TARGET_RADIUS / sum : 0;
    return {
      uL1: l[0] * scale, uL2: l[1] * scale, uL3: l[2] * scale, uL4: l[3] * scale,
      uA: recipe.a, uB: recipe.b, uC: recipe.c, uD: recipe.d,
      uThickness: get('Thickness', 0.5) * 0.035,
      uHueOffset: get('Hue Offset', 0),
      uHueSweep: this.hueSweepCycles(recipe.petals, get('Hue Sweep', 0)),
      uDepth: get('Depth', 0.35),
      uMaxR: sum > 1e-5 ? TARGET_RADIUS : 0.001,
    };
  }
}
